# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: be_tools
version: '1.4.9'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/be_tools

page:
    title: 'translate:a1510_title'
    perm: be_tools[]
    icon: rex-icon fa-wrench
    subpages:
        default: { title: 'translate:a1510_default' }
        help: { title: 'translate:a1510_help', icon: rex-icon fa-info-circle, itemclass: pull-right }

requires:
    redaxo: '^5.3.0'
